# Generated by Django 2.2.4 on 2019-09-05 05:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMaster',
            fields=[
                ('school_code', models.IntegerField(primary_key=True, serialize=False)),
                ('diascode', models.CharField(max_length=50, null=True)),
                ('school_nm_e', models.CharField(max_length=100, null=True)),
                ('school_nm_h', models.CharField(max_length=100, null=True)),
                ('dist_cd', models.CharField(max_length=100, null=True)),
                ('dist_nm', models.CharField(max_length=100, null=True)),
                ('b_cd', models.CharField(max_length=100, null=True)),
                ('block_nm_e', models.CharField(max_length=100, null=True)),
                ('block_nm_h', models.CharField(max_length=100, null=True)),
                ('gp_cd', models.CharField(max_length=100, null=True)),
                ('gp_nm_h', models.CharField(max_length=100, null=True)),
                ('gp_nm_e', models.CharField(max_length=100, null=True)),
                ('vill_cd', models.CharField(max_length=100, null=True)),
                ('vill_nm_h', models.CharField(max_length=100, null=True)),
                ('vill_nm_e', models.CharField(max_length=100, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='schoolselfies',
            name='sch_selfie',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
