# Generated by Django 2.2.4 on 2019-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_surveyor_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor_registration',
            name='surveyor_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
