# Generated by Django 2.2.4 on 2019-09-09 05:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_auto_20190907_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=500, null=True)),
                ('teacher_designation', models.CharField(max_length=100, null=True)),
                ('attendance', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
