# Generated by Django 2.2.4 on 2019-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_hrteachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrteachers',
            name='date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hrteachers',
            name='school_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
