# Generated by Django 2.2.4 on 2019-09-09 06:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_auto_20190909_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=500, null=True)),
                ('date', models.CharField(max_length=500, null=True)),
                ('building', models.CharField(max_length=500, null=True)),
                ('terrace', models.CharField(max_length=500, null=True)),
                ('numRooms', models.CharField(max_length=500, null=True)),
                ('enoughRooms', models.CharField(max_length=500, null=True)),
                ('seats', models.CharField(max_length=500, null=True)),
                ('toilet', models.CharField(max_length=500, null=True)),
                ('cleanToilet', models.CharField(max_length=500, null=True)),
                ('waterInToilet', models.CharField(max_length=500, null=True)),
                ('approachRoad', models.CharField(max_length=500, null=True)),
                ('roadType', models.CharField(max_length=500, null=True)),
                ('waterSrc', models.CharField(max_length=500, null=True)),
                ('boundary', models.CharField(max_length=500, null=True)),
                ('ground', models.CharField(max_length=500, null=True)),
                ('powerCon', models.CharField(max_length=500, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
