# Generated by Django 2.2.4 on 2019-09-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_middaymealquality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolselfies',
            name='name',
        ),
    ]
