# Generated by Django 2.2.4 on 2019-09-13 06:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0014_auto_20190913_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDMDataDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField(null=True)),
                ('dCode', models.CharField(max_length=500, null=True)),
                ('schName', models.CharField(max_length=500, null=True)),
                ('devBlk', models.CharField(max_length=500, null=True)),
                ('agencyName', models.CharField(max_length=500, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
