# Generated by Django 2.2.4 on 2019-09-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0016_teachersdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdmdata',
            name='remark',
        ),
    ]
