# Generated by Django 2.2.4 on 2019-09-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0018_auto_20190924_0856'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hrteachers',
            table=None,
        ),
        migrations.AlterModelTable(
            name='infrastructuredetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mdmdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mdmdatadetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='middaymealquality',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolmaster',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolselfies',
            table=None,
        ),
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
        migrations.AlterModelTable(
            name='surveyor_registration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teachersdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teachingquality',
            table=None,
        ),
    ]
