# Generated by Django 2.2.4 on 2019-09-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0019_auto_20190924_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolselfies',
            old_name='image',
            new_name='sch_selfie',
        ),
        migrations.RemoveField(
            model_name='schoolselfies',
            name='schName',
        ),
    ]
